### ISSUE TITLE
When I Learning your project, I have some questions

### ISSUE THREAD

**Issue by WangShuoran** [redchenjs/nfc_attendence_system_esp32#1]
In your `main/src/core/os.c`, I find some code:
```
    ESP_ERROR_CHECK(esp_event_loop_create_default());

    ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT, ESP_EVENT_ANY_ID, &wifi_event_handler, NULL));
    ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT, ESP_EVENT_ANY_ID, &ip_event_handler, NULL));
    ESP_ERROR_CHECK(esp_event_handler_register(SC_EVENT, ESP_EVENT_ANY_ID, &sc_event_handler, NULL));

```
Those mean create a default event loop, and put any event to this loop.

I want to know `WIFI_EVENT`, `IP_EVENT`, `SC_EVENT` mean what, I can't check with IDE "Go to definition" or "Go to declaration"

I google of this, I see [in this website](https://docs.espressif.com/projects/espressif-esp-moonlight/zh_CN/latest/wifi.html) he also set same name to this position.

I want to know want it is?

The manual is [this](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/esp_event.html?highlight=esp_event_handler_register#_CPPv426esp_event_handler_register16esp_event_base_t7int32_t19esp_event_handler_tPv):

<img width="545" alt="image" src="https://user-images.githubusercontent.com/43474491/160992577-1635b1b4-7656-4a2e-8688-0be8d7b30148.png">
<img width="525" alt="image" src="https://user-images.githubusercontent.com/43474491/160992470-cb46835b-2714-49e2-8fb5-0b7bdd3f7685.png">

when I try to go to definition:
<img width="541" alt="image" src="https://user-images.githubusercontent.com/43474491/160993187-e00a86c2-6352-423d-b98e-d295f5fd4cea.png">

And when I learn freertos, in xTaskCreate also set pcName as string. Does those is one type thing?
<img width="493" alt="image" src="https://user-images.githubusercontent.com/43474491/160993244-a102161c-2dae-4c72-8491-e91a6477e9b6.png">

Thank you!

**Comment by redchenjs** [comment]
Hi @WangShuoran, WIFI_EVENT is defined here: [esp-idf/components/esp_wifi/include/esp_wifi_types.h#L610](https://github.com/espressif/esp-idf/blob/e29e96101d2885b5e510645d0ea18fb653b813be/components/esp_wifi/include/esp_wifi_types.h#L610)

You can also take a look at this: https://github.com/espressif/esp-idf/blob/3aeb80acb66038f14fc2a7606e7516a3e2bfa6c9/docs/en/api-reference/system/esp_event.rst

**Comment by WangShuoran** [comment]
I understand, Thank you for confirmation.

the pass code is setting the `esp_event_handler_instance_register` needed first parameter:
```
ESP_EVENT_DECLARE_BASE(WIFI_EVENT);
......
esp_event_handler_instance_register(WIFI_EVENT, ...);
```

Thank you again!
